### ISSUE TITLE
Permissive License?

### ISSUE THREAD

**Issue by nodev** [ayebear/es#10]
Hi,

Was just wondering why did you choose LGPL over something like BSD or MIT for such a small library? I don't think LGPL allows static linking with non-compatible (or closed source) licenses and it'd be an annoyance to link it dynamically for such a small library.

**Comment by ayebear** [comment]
That's a good point. The reason I initially chose LGPL was to keep the library open source without it being hidden away in proprietary software, but I've since changed my views. I'd rather have it be as convenient as possible to use, so I will change the license to something permissive like MIT.

**Comment by nodev** [comment]
Thanks.
