### ISSUE TITLE
begin/end functions for es::World

### ISSUE THREAD

**Issue by Scipi** [ayebear/es#4]
es::World requires begin()/end() functions in order to work properly with ranged-based for loops. Currently, code such as this one taken from the system examples gives an error in VS2015:

``` C++
for (auto& ent: world){
    auto pos = ent.get<Position>();
    auto vel = ent.get<Velocity>();
    if (pos && vel){
        pos->x += vel->x * dt;
        pos->y += vel->y * dt;
    }
}
```

**Comment by ayebear** [comment]
You can do world.query() for now, but I will add this soon.

**Comment by ayebear** [comment]
The readme was updated to use world.query(). Ideally this would work with begin()/end(), but the way the entities are internally stored makes this tricky. It would only be worth adding if there was a performance benefit. A new issue has been added for the performance aspect of this: #7
