### ISSUE TITLE
entityPrototypeLoader.h requires configfile.h being in the project

### ISSUE THREAD

**Issue by Scipi** [ayebear/es#5]
Line 11 in include/es/entityprototypeloader.h includes configfile.h as such:

``` C++
#include "configfile.h"
```

Where configfile.h isn't a part of es.
I'd recommend adding a folder inside include/es like extlibs, cfgfile, etc for these headers so users don't get that error the first time they compile and the project doesn't have the cfgfile include directory added to the search path.

**Comment by ayebear** [comment]
The include directories for ConfigFile are part of the CMake configuration, so this should work fine. The actual code is in the git submodule "es/lib/ConfigFile". Make sure you pull this with "git submodule init" and "git submodule update".

I'll use &lt;header.h&gt; syntax over "header.h" for the includes though. There are other files that depend on the include paths being setup correctly, so this isn't the only case.

Edit: So you mean to add the git submodules inside the es/include folder? I could do that but things would get messy when including more libraries. So I think that should be more of a build system thing than hard-coded include paths.

**Comment by Scipi** [comment]
It should be somewhere to where other projects using es don't necessarily need to know about configfile.

**Comment by ayebear** [comment]
I will update the readme to explain this.
